### ISSUE TITLE
Switch from Witness plugin to Gradle built-in dependency checksums verification

### ISSUE THREAD

**Issue by Vovchyk** [rsksmart/rskj#1255]
Right now the `witness` gradle plugin is being used for dependencies’ checksums verification. But it seems that this plugin is kinda a bit outdated. It doesn't support gradle versions >= 5.0 (right now the project uses gradle distribution v4.7, and the latest available is v6.5). There’s an open issue for `witness` to support gradle 5+ - https://github.com/signalapp/gradle-witness/issues/30.

Starting from v6.2 Gradle has a built-in mechanism to verify dependency checksums, which could be used instead of `witness`. More info [here](https://docs.gradle.org/6.2/userguide/dependency_verification.html#sec:checksum-verification) and [here](https://docs.gradle.org/current/userguide/dependency_verification.html).

**Comment by bcodesido** [comment]
The `witness` that we're using is not the original. We are using our [own forked and modified version](https://github.com/rsksmart/gradle-witness) because the original one loss support or at least they didn't add some features that are useful.

Im sure that a built-in dependency check will be better because we don't have to still managing our own version or adding a external plugin, but we need to be sure that accomplish our requirements:

- Check runtime, build and test dependencies.
- Shows clearly the differences when dependencies are modified and the hashes of those dependencies are verifiable.
- Easy to use and to integrate.
- Doesn't interfere with the reproducible build.

If you've the time, go ahead.
