### ISSUE TITLE
High CPU usage (100% single core)

### ISSUE THREAD

**Issue by peername** [rsksmart/rskj#776]
We are running RSK full node. But the process is very CPU intensive. It is using 100% of one single thread/CPU core all the time. The blockchain is synced. We thought that after sync CPU usage will be lower.

**Comment by tinchou** [comment]
Optimizing the node is part of our continuous effort to allow our network to scale, and we will strive to make it fit into a single core CPU. For now, I suggest sticking with the posted minimum requirements: https://github.com/rsksmart/rskj/wiki/Node-Minimum-Requirements

I will close this issue now because it is non-actionable, but feel free to open a new one if you find a specific issue or bottleneck we can fix.

Thanks!

**Comment by peername** [comment]
We are running it on a server. We want to support the network by runnging the RSK full node. But the CPU usage is not normal. 100% on a single thread, on a synced node is a signal that something is not right.
